



FROM python:3.8-slim

 

# Set the working directory in the container

 

WORKDIR /testwork

COPY asc.py /testwork/

# Run the Python script when the container launches

 

ENTRYPOINT ["python", "/testwork/asc.py"]

 
